trigger:
  branches:
    include:
      - main

pool:
  name: Default
  demands:
    - agent.name -equals techzoos
    - maven

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11'  # Installs Java 11
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'AzureStorage'  # You can also use 'LocalDirectory' if you have a local JDK

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'Path'  # Use the installed Java path
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
