trigger:
  branches:
    include:
      - main  # Specify the branch you're working on

pool:
  name: Default
  demands:
    - agent.name -equals techzoos
    - maven  # Ensure Maven is required by the agent

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'  # Ensure pom.xml is located at the root of your repository or adjust the path
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'  # Use the JDK version compatible with your project
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
